server:
  port: ${PORT:9090}

spring:
  sql:
    init:
      mode: never # data.sql 실행
  datasource:
    url: jdbc:mariadb://${DB_URL:mariadb:3309}/blog?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USER:motolies}
    password: ${DB_PASS:motolies!!}
    hikari:
      pool-name: blogHikariCP
      connection-timeout: 30000
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 300000
      max-lifetime: 1800000
      auto-commit: true
      leak-detection-threshold: 5000
  jmx:
    default-domain: blog
  jpa:
    properties:
      hibernate:
        release_mode: AFTER_TRANSACTION
        dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: validate
      naming.physical-strategy: kr.hvy.blog.infra.config.HvyPhysicalNamingStrategy
    defer-datasource-initialization: true
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  jackson:
    deserialization:
      fail-on-unknown-properties: false
    serialization:
      indent-output: true
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      timeout: 3600
  cloud:
    stream:
      kafka:
        enabled: false # kafka 사용 여부

hvy:
  sql:
    datasource-wrapper:
      enable-wrapper: true
      format: true
      slow-query-threshold: 500
      data-source-names:
        - "dataSource"

#Configure Mybatis
mybatis:
  type-aliases-package: kr.hvy.blog.modules,kr.hvy.common.mybatis.CountMapper # 많아지면 콤마로 구분
  type-handlers-package: kr.hvy.common.code
  mapper-locations: classpath:mybatis-mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: NULL

# log
logging:
  level:
    org.springframework:
      web: ERROR
    org.mybatis: DEBUG
    com.zaxxer:
        hikari: ERROR
        hikari.HikariConfig: DEBUG
    kr.hvy:
      common.infrastructure.database.logging: DEBUG
      blog:
        service: TRACE
        controller: TRACE
        security: ERROR
        repository: TRACE
        mapper: TRACE
  logback:
    rollingpolicy:
      max-history: 7
      max-size: 10MB

# jwt
jwt:
  header:
    name: Authorization
    prefix: Bearer
  secret: ${JWT_SECRET:jwt_secret_key!!@@longlongKey1234}
  expiration: 31449600
  refresh:
    expiration: 31449600

# file
path.upload: ${FILE_PATH:${user.home}/skyscape/file}

# slack
slack:
  token: ${SLACK_BOT_TOKEN:xoxb-xxxxxxxxxxxx-xxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxx}

# jira
jira:
  url: ${JIRA_URL:https://your-company.atlassian.net}
  username: ${JIRA_USERNAME:your-email@company.com}
  api-token: ${JIRA_API_TOKEN:your-api-token}
  project-key: ${JIRA_PROJECT_KEY:PROJECT}

# scheduler
scheduler:
  public-ip:
    lock-name: PUBLIC-IP-TEST
    cron-expression: "0 0 0 * * ?"
  ppomppu:
    lock-name: PPOMPPU-TEST
    cron-expression: "*/10 * * * * ?"
  log-cleaner:
    lock-name: LOGCLEANER-TEST
    cron-expression: "*/10 * * * * ?"
  jira:
    lock-name: JIRA-SYNC-TEST
    cron-expression: "0 0 0 1 * ?"

cookie:
  same-site: LAX
  secure: false


---
spring:
  config:
    activate:
      on-profile: prod
# scheduler
scheduler:
  public-ip:
    lock-name: PUBLIC-IP-PROD
    cron-expression: "0 * * * * ?"
  ppomppu:
    lock-name: PPOMPPU-PROD
    cron-expression: "* */10 * * * ?"
  log-cleaner:
    lock-name: LOGCLEANER-PROD
    cron-expression: "* * 0 * * ?"
  jira:
    lock-name: JIRA-SYNC-PROD
    cron-expression: "0 0 * * * ?"

cookie:
  same-site: NONE
  secure: true