# server
server:
  port: ${PORT:9090}
  forward-headers-strategy: framework

spring:
  sql:
    init:
      mode: never # data.sql 실행
  datasource:
    url: jdbc:mariadb://${DB_URL:mariadb:3309}/blog?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USER:motolies}
    password: ${DB_PASS:motolies!!}
    hikari:
      pool-name: blogHikariCP
      connection-timeout: 30000
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 300000
      max-lifetime: 1800000
      auto-commit: true
      leak-detection-threshold: 5000
  jmx:
    default-domain: blog
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        type: trace
        release_mode: AFTER_TRANSACTION
        dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: validate
      naming.physical-strategy: kr.hvy.blog.infra.config.HvyPhysicalNamingStrategy
    defer-datasource-initialization: true
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  jackson:
    deserialization:
      fail-on-unknown-properties: false
    serialization:
      indent-output: true
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      timeout: 3600

#Configure Mybatis
mybatis:
  type-aliases-package: kr.hvy.blog.modules,kr.hvy.common.mybatis.CountMapper # 많아지면 콤마로 구분
  mapper-locations: classpath:mybatis-mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: NULL

# log
logging:
  level:
    org:
      springframework.web: ERROR
#      hibernate:
#        SQL: TRACE
#        stat: TRACE
#        type.descriptor.sql.BasicBinder: TRACE
      mybatis: DEBUG
    com:
      zaxxer.hikari: ERROR
      zaxxer.hikari.HikariConfig: DEBUG
    kr.hvy.blog:
      service: TRACE
      controller: TRACE
      security: ERROR
      repository: TRACE
      mapper: TRACE
    io.github.motolies: DEBUG
  logback:
    rollingpolicy:
      max-history: 7
      max-size: 10MB

# jwt
jwt:
  header:
    name: Authorization
    prefix: Bearer
  secret: ${JWT_SECRET:jwt_secret_key!!@@longlongKey1234}
  expiration: 31449600
  refresh:
    expiration: 31449600

# file
path.upload: ${FILE_PATH:${user.home}/skyscape/file}

# springdoc
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui

# slack
slack:
  token: ${SLACK_BOT_TOKEN:xoxb-xxxxxxxxxxxx-xxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxx}


# scheduler
scheduler:
  public-ip:
    lock-name: PUBLIC-IP-TEST
    cron-expression: "*/10 * * * * ?"
  ppomppu:
    lock-name: PPOMPPU-TEST
    cron-expression: "*/10 * * * * ?"

cookie:
  same-site: LAX
  secure: false

---
spring:
  config:
    activate:
      on-profile: prod
# scheduler
scheduler:
  public-ip:
    lock-name: PUBLIC-IP-PROD
    cron-expression: "0 * * * * ?"
  ppomppu:
    lock-name: PPOMPPU-PROD
    cron-expression: "* */10 * * * ?"

cookie:
  same-site: NONE
  secure: true